### Configurations from config server
discovery-service-user:
  server:
    hostname: localhost #discovery-user profile property
    port: 8010 #discovery-user profile properdiscovery
  credentials:
    username: user
    password: pass
#
kafka-user:
  hostname: test
###

spring:
  application:
    name: discovery-service
  profiles:
    active: discovery-service-user
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8012}

server:
  port: ${discovery-service-user.server.port}

eureka:
  instance:
    hostname: ${discovery-service-user.server.hostname}
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${discovery-service-user.server.hostname}:${discovery-service-user.server.port}/eureka


management:
  endpoint:

    restart:
      access: unrestricted
    shutdown:  #client
      access: unrestricted
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, shutdown, restart
