name: Publish Docker Image
on:
  push:
    branches:
      - 'release/**'

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Copy Files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
          ls -a
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        run: |
          docker build -t mrshoffen/task-tracker-discovery-service:latest .
          docker images
          docker push mrshoffen/task-tracker-discovery-service:latest
